
package interfaz;

import clase.Articulo;
import clase.Producto;
import decorator.Garantia;
import decorator.EnvioExpress;
import tiendaonline.TiendaVirtual;

/**
 *
 * @author Abel
 */
public class DetalleProducto extends javax.swing.JPanel {

    private final TiendaVirtual tienda = TiendaVirtual.getInstancia();
    private Menu menuPadre;
    private Articulo articuloActual;

    /** Constructor para el Form Designer */
    public DetalleProducto() {
        initComponents();
        centrar();
    }

    /** Constructor para CardLayout de Menu */
    public DetalleProducto(Menu menu) {
        initComponents();
        this.menuPadre = menu;
        centrar();
    }

    private void centrar() {
        setLayout(new java.awt.BorderLayout());
        removeAll();
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }

    /**
     * Carga el artículo en el panel.
     * Llamado desde Menu.mostrarDetalle(Articulo).
     */
    public void setArticulo(Articulo art) {
        this.articuloActual = art;
        jLabel1.setText(art.getNombre());
        jLabel2.setText("Categoría: " + art.getCategoria());
        jLabel3.setText("Stock: " + art.getStock());

        try {
            String nombreImg = art.getNombre().replace("\"", "");
            java.net.URL url = getClass().getResource("/imagenes/productos/" + nombreImg + ".jpg");
            if (url != null) {
                java.awt.Image img = new javax.swing.ImageIcon(url).getImage()
                    .getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
                jLabel4.setIcon(new javax.swing.ImageIcon(img));
                jLabel4.setText("");
            } else {
                jLabel4.setIcon(null);
                jLabel4.setText("[ sin imagen ]");
            }
        } catch (Exception e) {
            jLabel4.setIcon(null);
            jLabel4.setText("[ sin imagen ]");
        }
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        if (art.getStock() <= 0) {
            btnAgregarCarro.setText("AGOTADO");
            btnAgregarCarro.setEnabled(false);
            jLabel3.setForeground(java.awt.Color.RED);
        } else {
            btnAgregarCarro.setText("Agregar al carrito");
            btnAgregarCarro.setEnabled(true);
            jLabel3.setForeground(null);
        }
        actualizarTotal();
    }

    /** Recalcula el total con los decoradores seleccionados */
    private void actualizarTotal() {
        if (articuloActual == null) return;
        double total = articuloActual.getPrecio();
        if (jCheckBox1.isSelected()) total += 200.0; // Garantia
        if (jCheckBox2.isSelected()) total += 30.0;  // Envio Express
        jLabel6.setText("TOTAL: S/ " + String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarCarro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 45, -1, -1));

        jLabel1.setText("NOMBRE DEL PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel2.setText("Categoria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel3.setText("Stock");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        btnAgregarCarro.setText("Agregar al carrito");
        btnAgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarroActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        jLabel4.setText("ING");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel5.setText("AGREGADOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jCheckBox1.setText("Garantia");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jCheckBox2.setText("Envio express");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel6.setText("TOTAL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/detalle_producto.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -70, 480, 870));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1050, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarroActionPerformed
        if (articuloActual == null) return;
        if (articuloActual.getStock() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Este producto está agotado.", "Sin stock",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar permiso (replica lógica del proxy)
        state.Pedido pedido = tienda.getPedidoActual();
        String estado = pedido.getNombreEstado();
        if (estado.equals("sin_registro") || estado.equals("pendiente_registro")) {
            pedido.setEstado(new state.PendienteRegistro());
            if (menuPadre != null) menuPadre.mostrarLogin("DETALLE");
            return;
        }

        Producto producto = articuloActual;
        if (jCheckBox1.isSelected()) producto = new Garantia(producto);
        if (jCheckBox2.isSelected()) producto = new EnvioExpress(producto);

        pedido.getCarrito().agregar(producto);
        if (menuPadre != null) menuPadre.actualizarCarritoBtn();
        javax.swing.JOptionPane.showMessageDialog(this,
            "\"" + producto.getNombre() + "\" agregado.\nPrecio: S/ "
                + String.format("%.2f", producto.getPrecio()),
            "Agregado al carrito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgregarCarroActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (menuPadre != null) menuPadre.mostrarPanel(menuPadre.getPanelAnterior());
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        actualizarTotal();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        actualizarTotal();
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
