package interfaz;

public class DetallePago extends javax.swing.JPanel {

    private final tiendaonline.TiendaVirtual tienda = tiendaonline.TiendaVirtual.getInstancia();
    private Menu menuPadre;

    /** Constructor para el Form Designer */
    public DetallePago() {
        initComponents();
        configurar();
    }

    /** Constructor para CardLayout de Menu */
    public DetallePago(Menu menu) {
        initComponents();
        this.menuPadre = menu;
        configurar();
    }

    private void configurar() {
        setLayout(new java.awt.BorderLayout());
        removeAll();
        add(jPanel1, java.awt.BorderLayout.CENTER);
        txtBoleta.setEditable(false);
    }

    /** Carga todos los datos del pedido confirmado. Llamado desde Menu.mostrarConfirmacion(). */
    public void actualizar() {
        state.Pedido pedido = tienda.getPedidoActual();

        // Capturar valores ANTES de resetear el pedido
        double subtotal     = pedido.getCarrito().getPrecio();
        int    descuento    = pedido.getDescuentoPuntos();
        double total        = pedido.getMontoTotal();
        int    ptsCanjeados = pedido.getPuntosCanjeados();
        int    ptsGanados   = (int) total;

        clase.Usuario u = pedido.getUsuario();
        jLabel2.setText("Cliente: " + (u != null ? u.getNombreCompleto() : "—"));


        String dir  = pedido.getDireccionEnvio() != null ? pedido.getDireccionEnvio() : "-";
        String tel  = pedido.getNumero() != null ? pedido.getNumero() : "-";
        String fecha;
        try {
            java.time.LocalDate ld = java.time.LocalDate.parse(pedido.getFechaEstimadaEntrega());
            fecha = ld.format(java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        } catch (Exception ex) {
            fecha = pedido.getFechaEstimadaEntrega() != null ? pedido.getFechaEstimadaEntrega() : "-";
        }

        // Construir boleta como texto plano con fuente monoespaciada
        StringBuilder sb = new StringBuilder();
        sb.append("======================================================\n");
        sb.append(String.format("%-22s %s%n", "PRODUCTO", "PRECIO"));
        sb.append("--------------------------------\n");
        for (clase.Producto p : pedido.getCarrito().getItems()) {
            String nom = p.getNombre().length() > 21
                ? p.getNombre().substring(0, 21) + "." : p.getNombre();
            sb.append(String.format("%-22s S/ %.2f%n", nom, p.getPrecio()));
        }
        sb.append("------------------------------------------------------\n");
        sb.append(String.format("%-22s S/ %.2f%n", "Subtotal:", subtotal));
        if (descuento > 0) {
            sb.append(String.format("%-22s -S/ %.2f%n", "Descuento puntos:", (double) descuento));
        }
        sb.append(String.format("%-22s S/ %.2f%n", "TOTAL:", total));
        if (descuento > 0) {
            sb.append(String.format("%-22s -%d pts%n", "Pts canjeados:", ptsCanjeados));
        }
        sb.append(String.format("%-22s +%d pts%n", "Pts ganados:", ptsGanados));
        sb.append("------------------------------------------------------\n");
        sb.append(String.format("%-22s %s%n", "Direccion:", dir));
        sb.append(String.format("%-22s %s%n", "Entrega estimada:", fecha));
        sb.append(String.format("%-22s %s%n", "Telefono:", tel));
        sb.append("========================================================\n");

        txtBoleta.setContentType("text/plain");
        txtBoleta.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        txtBoleta.setForeground(java.awt.Color.BLACK);
        txtBoleta.setBackground(java.awt.Color.WHITE);
        txtBoleta.setText(sb.toString());
        txtBoleta.setEditable(false);
        txtBoleta.setCaretPosition(0);

        // Pedido completado — resetear DESPUÉS de capturar todos los datos
        tienda.nuevoPedido();
        if (menuPadre != null) menuPadre.actualizarCarritoBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBoleta = new javax.swing.JTextPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PEDIDO CONFIRMADO!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 51, -1, -1));

        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 163, -1, -1));

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        jButton2.setText("Recordatorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        btnComprar.setText("SEGUIR COMPRANDO");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jScrollPane3.setViewportView(txtBoleta);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 360, 340));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                             

    state.Pedido pedido = tienda.getPedidoActual(); 

// Validación rápida por si no hay pedido activo
if (pedido == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "No hay ningún pedido actual para enviar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

// 1. Extraemos solo los datos solicitados: cliente, producto y total
String cliente = (pedido.getUsuario() != null) ? pedido.getUsuario().getNombreCompleto() : "Anónimo";  

// CORREGIDO: Se agregó la comilla doble antes de No Especificado
String producto = (pedido.getDireccionEnvio() != null) ? pedido.getDireccionEnvio() : "No Especificado";

// 2. Creamos el JSON limpio solo con esos tres campos
String jsonInputString = String.format(  
    "{\"cliente\": \"%s\", \"producto\": \"%s\", \"total\": %.2f}",  
    cliente,  
    producto,  
    pedido.getMontoTotal()  
); 

// 3. Ejecutamos la petición HTTP en un hilo secundario para no congelar la UI
new Thread(() -> {  
    try {  
        java.net.URL url = java.net.URI.create("https://n8n.buypal.com.pe/webhook/Diseno_Patrones").toURL();
        java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();

        conn.setRequestMethod("POST");  
        conn.setRequestProperty("Content-Type", "application/json; utf-8");  
        conn.setRequestProperty("Accept", "application/json");  
        conn.setDoOutput(true); 

        // Enviamos el JSON  
        try (java.io.OutputStream os = conn.getOutputStream()) {  
            byte[] input = jsonInputString.getBytes("utf-8");  
            os.write(input, 0, input.length);  
        } 

        // Leemos la respuesta de n8n  
        int code = conn.getResponseCode();  
        if (code == 200 || code == 201) {  
            System.out.println("¡Datos enviados con éxito! Código: " + code);  
            javax.swing.SwingUtilities.invokeLater(() -> {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Pedido enviado a Whatsapp exitosamente!");
            });
        } else {  
            System.err.println("[n8n] Error en el servidor. Código: " + code);  
            javax.swing.SwingUtilities.invokeLater(() -> {
                javax.swing.JOptionPane.showMessageDialog(this, "n8n respondió con error. Código: " + code, "Error Servidor", javax.swing.JOptionPane.ERROR_MESSAGE);
            });
        }  
        conn.disconnect(); 

    } catch (Exception e) {  
        System.err.println("[n8n] Error al conectar con el webhook: " + e.getMessage());  
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo conectar con n8n:\n" + e.getMessage(), "Error de Conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
        });
    }  
}).start();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // VOLVER: regresa al catálogo sin reiniciar el pedido
        if (menuPadre != null) menuPadre.mostrarPanel("CATALOGO");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (menuPadre != null) menuPadre.mostrarPanel("CATALOGO");
    }//GEN-LAST:event_btnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtBoleta;
    // End of variables declaration//GEN-END:variables
}
