
package interfaz;

/**
 *
 * @author Abel
 */
public class TipoPago extends javax.swing.JPanel {

    private final tiendaonline.TiendaVirtual tienda = tiendaonline.TiendaVirtual.getInstancia();
    private Menu menuPadre;
    private javax.swing.ButtonGroup grupoMetodo;

    /** Constructor para el Form Designer */
    public TipoPago() {
        initComponents();
        configurar();
    }

    /** Constructor para CardLayout de Menu */
    public TipoPago(Menu menu) {
        initComponents();
        this.menuPadre = menu;
        configurar();
    }

    private void configurar() {
        setLayout(new java.awt.BorderLayout());
        removeAll();
        add(jPanel1, java.awt.BorderLayout.CENTER);
        grupoMetodo = new javax.swing.ButtonGroup();
        grupoMetodo.add(rdbTarjeta);
        grupoMetodo.add(rdbYape);
        grupoMetodo.add(rdbPaypal);
    }

    /** Actualiza el total mostrado. Llamado desde Menu.mostrarPago(). */
    public void actualizar() {
        state.Pedido pedido = tienda.getPedidoActual();
        pedido.setDescuentoPuntos(0);
        pedido.setPuntosCanjeados(0);

        clase.Usuario u = tienda.getUsuarioActual();
        double total = pedido.getCarrito().getPrecio();

        if (u != null && u.getPuntos() >= 100) {
            int puntos         = u.getPuntos();
            // Cuántos soles puede descontar (100 pts = S/10)
            int descuentoMax   = (puntos / 100) * 10;
            int descuentoReal  = (int) Math.min(descuentoMax, total);
            int puntosNecesarios = (descuentoReal / 10) * 100;

            int resp = javax.swing.JOptionPane.showConfirmDialog(this,
                "🎁 Tienes " + puntos + " puntos de fidelidad.\n" +
                "Puedes descontar S/ " + descuentoReal + ".00 usando " + puntosNecesarios + " puntos.\n\n" +
                "¿Quieres aplicar el descuento ahora?",
                "Canjear puntos", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (resp == javax.swing.JOptionPane.YES_OPTION) {
                pedido.setDescuentoPuntos(descuentoReal);
                pedido.setPuntosCanjeados(puntosNecesarios);
                total -= descuentoReal;
            }
        }

        jLabel2.setText("TOTAL A PAGAR: S/ " + String.format("%.2f", total));
        grupoMetodo.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbTarjeta = new javax.swing.JRadioButton();
        rdbYape = new javax.swing.JRadioButton();
        rdbPaypal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel1.setText("METODO DE PAGO");

        jLabel2.setText("TOTAL A PAGAR:");

        rdbTarjeta.setText("Tarjeta de credito / debito");
        rdbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTarjetaActionPerformed(evt);
            }
        });

        rdbYape.setText("Yape");
        rdbYape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbYapeActionPerformed(evt);
            }
        });

        rdbPaypal.setText("Paypal");
        rdbPaypal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPaypalActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_yape.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbTarjeta)
                    .addComponent(jLabel1)
                    .addComponent(rdbYape)
                    .addComponent(rdbPaypal)
                    .addComponent(jLabel2)
                    .addComponent(btnPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rdbTarjeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbYape)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbPaypal)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPagar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String metodo = null;
        if (rdbTarjeta.isSelected())      metodo = "tarjeta";
        else if (rdbYape.isSelected()) metodo = "yape";
        else if (rdbPaypal.isSelected()) metodo = "paypal";

        if (metodo == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione un método de pago.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        state.Pedido pedido = tienda.getPedidoActual();
        pedido.setMetodoPago(metodo);

        proxy.CatalogoProxy proxy = new proxy.CatalogoProxy();
        boolean ok = proxy.procesarPago(pedido, metodo);
        if (ok) {
            pedido.avanzar(); // registro_datos_pago → procesado_pago
            pedido.avanzar(); // procesado_pago → datos_envio
            if (menuPadre != null) menuPadre.mostrarEnvio();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se pudo procesar el pago. Verifique su estado de sesión.", "Error de pago",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void rdbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTarjetaActionPerformed
        // ButtonGroup maneja la exclusión mutua automáticamente
    }//GEN-LAST:event_rdbTarjetaActionPerformed

    private void rdbYapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbYapeActionPerformed
        // ButtonGroup maneja la exclusión mutua automáticamente
    }//GEN-LAST:event_rdbYapeActionPerformed

    private void rdbPaypalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPaypalActionPerformed
        // ButtonGroup maneja la exclusión mutua automáticamente
    }//GEN-LAST:event_rdbPaypalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbPaypal;
    private javax.swing.JRadioButton rdbTarjeta;
    private javax.swing.JRadioButton rdbYape;
    // End of variables declaration//GEN-END:variables
}
